# Generated by Django 5.2.15 on 2026-06-23 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thể loại nhạc',
                'verbose_name_plural': 'Thể loại nhạc',
                'db_table': 'music_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('song', 'Bài hát'), ('comment', 'Bình luận'), ('user', 'Người dùng')], db_index=True, max_length=10)),
                ('target_id', models.UUIDField(db_index=True, verbose_name='ID đối tượng')),
                ('reason', models.CharField(choices=[('copyright', 'Vi phạm bản quyền'), ('spam', 'Spam'), ('offensive', 'Nội dung sản phẩm'), ('other', 'Lý do khác')], max_length=20)),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('resolved', 'Đã xử lý'), ('dismissed', 'Bỏ qua')], db_index=True, default='pending', max_length=15)),
                ('resolved_note', models.TextField(blank=True, default='', verbose_name='Ghi chú xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Admin xử lý')),
            ],
            options={
                'verbose_name': 'Báo cáo vi phạm',
                'db_table': 'music_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Tên bài hát')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='File audio')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/songs/', verbose_name='Ảnh bìa')),
                ('lyrics', models.TextField(blank=True, default='', verbose_name='Lời bài hát')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã phát hành'), ('hidden', 'Đã ẩn')], db_index=True, default='draft', max_length=15, verbose_name='Trạng thái')),
                ('allow_download', models.BooleanField(default=False, verbose_name='Cho phép tải')),
                ('is_trending', models.BooleanField(db_index=True, default=False, verbose_name='Trending')),
                ('play_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Lượt nghe')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Bài hát',
                'verbose_name_plural': 'Bài hát',
                'db_table': 'music_song',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Đã ẩn')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='music.comment', verbose_name='Comment cha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'db_table': 'music_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='music.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'music_comment_like',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(help_text='1-5 sao', verbose_name='Điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.song')),
            ],
            options={
                'db_table': 'music_rating',
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.CreateModel(
            name='ListenHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_history', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_history', to='music.song')),
            ],
            options={
                'db_table': 'music_listen_history',
                'ordering': ['-listened_at'],
                'indexes': [models.Index(fields=['user', 'song', 'listened_at'], name='history_user_song_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_likes', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.song')),
            ],
            options={
                'db_table': 'music_like',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
