# Generated by Django 5.2.15 on 2026-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hidden_by_admin',
            field=models.BooleanField(default=False, verbose_name='Bị khoá bởi Admin'),
        ),
        migrations.AddField(
            model_name='song',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do khoá'),
        ),
    ]
