# Generated by Django 5.2.15 on 2026-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_hidden_by_admin_song_hidden_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='appeal_message',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung kiến nghị'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_appealed',
            field=models.BooleanField(default=False, verbose_name='Đang có kiến nghị'),
        ),
        migrations.AlterField(
            model_name='song',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do bị khoá'),
        ),
    ]
