# Generated by Django 5.2.15 on 2026-07-10 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_appeal_message_song_is_appealed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Tên album')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/albums/', verbose_name='Ảnh bìa album')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã phát hành')], db_index=True, default='draft', max_length=15, verbose_name='Trạng thái')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
                'db_table': 'music_album',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='music.album', verbose_name='Album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_albums', to='music.song', verbose_name='Bài hát')),
            ],
            options={
                'verbose_name': 'Bài hát trong album',
                'verbose_name_plural': 'Bài hát trong album',
                'db_table': 'music_album_song',
                'ordering': ['order', 'added_at'],
                'unique_together': {('album', 'song')},
            },
        ),
    ]
