# Generated by Django 5.2.14 on 2026-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_add_album_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audio/', verbose_name='File audio'),
        ),
    ]
