# Generated by Django 5.2.14 on 2026-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlistlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/playlists/', verbose_name='Ảnh bìa'),
        ),
        migrations.DeleteModel(
            name='PlaylistLike',
        ),
    ]
