# Generated by Django 5.2.14 on 2026-08-17 06:27

from django.db import migrations


def copy_display_name_to_username(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if getattr(user, 'display_name', None):
            user.username = user.display_name
            user.save(update_fields=['username'])

def copy_username_to_display_name(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if hasattr(user, 'display_name'):
            user.display_name = user.username
            user.save(update_fields=['display_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_username'),
    ]

    operations = [
        migrations.RunPython(copy_display_name_to_username, copy_username_to_display_name),
    ]
