# Generated by Django 5.2.14 on 2026-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mood_email_notification',
            field=models.BooleanField(default=False, verbose_name='Email gợi ý nhạc'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_song_notification',
            field=models.BooleanField(default=True, verbose_name='Thông báo bài hát mới'),
        ),
    ]
