# Generated by Django 5.2.14 on 2026-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_mood_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_mood',
            field=models.BooleanField(default=True, verbose_name='Hiển thị cảm xúc'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_playlists',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Playlist cá nhân'),
        ),
    ]
