# Generated by Django 5.2.15 on 2026-06-28 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Tên nghệ danh')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Giới thiệu nghệ sĩ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/artist', verbose_name='Ảnh bìa')),
                ('website_url', models.CharField(blank=True, default='', max_length=225, verbose_name='Website')),
                ('facebook_url', models.CharField(default='', max_length=255, verbose_name='Facebook')),
                ('youtube_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Youtube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Nghệ sĩ')),
            ],
            options={
                'verbose_name': 'Hồ sơ nghệ sĩ',
                'verbose_name_plural': 'Hồ sơ nghệ sĩ',
                'db_table': 'artists_artist_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
