# Generated by Django 5.2.15 on 2026-07-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='cover_image',
        ),
    ]
