# Generated by Django 5.2.15 on 2026-06-29 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Trạng thái')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods', to='music.song', verbose_name='Bài hát đính kèm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tâm trạng',
                'verbose_name_plural': 'Tâm trạng',
                'db_table': 'social_mood',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày theo dõi')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Người theo dõi')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Người được theo dõi')),
            ],
            options={
                'verbose_name': 'Theo dõi',
                'verbose_name_plural': 'Theo dõi',
                'db_table': 'social_follow',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='FriendActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('playing', 'Đang nghe'), ('liked', 'Đã thích'), ('mood', 'Cập nhật tâm trạng')], db_index=True, max_length=10)),
                ('extra_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Nội dung bổ sung')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_activities', to='music.song', verbose_name='Bài hát liên quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_activities', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hoạt động bạn bè',
                'verbose_name_plural': 'Hoạt động bạn bè',
                'db_table': 'social_friend_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_user_time_idx')],
            },
        ),
    ]
