# Generated by Django 5.2.15 on 2026-07-05 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_followrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Vui vẻ, Buồn man mác, Thư giãn...', max_length=100, unique=True, verbose_name='Tên cảm xúc')),
                ('emoji', models.CharField(help_text='Emoji đại diện cho cảm xúc này, VD: 😎, 🌧️, 🧘', max_length=10, verbose_name='Emoji')),
                ('description', models.CharField(blank=True, default='', help_text='VD: Tràn đầy năng lượng', max_length=200, verbose_name='Mô tả ngắn')),
                ('gradient_from', models.CharField(default='#FFD194', help_text='Mã màu hex hoặc rgb, VD: #FFD194', max_length=30, verbose_name='Màu gradient bắt đầu')),
                ('gradient_to', models.CharField(default='#70E1F5', help_text='Mã màu hex hoặc rgb, VD: #70E1F5', max_length=30, verbose_name='Màu gradient kết thúc')),
                ('text_color', models.CharField(choices=[('dark', 'Chữ tối (dùng khi nền sáng)'), ('light', 'Chữ sáng (dùng khi nền tối)')], default='dark', max_length=10, verbose_name='Màu chữ')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Số nhỏ hơn sẽ hiển thị trước', verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ tick để ẩn cảm xúc này khỏi frontend', verbose_name='Đang kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại cảm xúc',
                'verbose_name_plural': 'Loại cảm xúc',
                'db_table': 'social_mood_type',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods', to='social.moodtype', verbose_name='Loại cảm xúc'),
        ),
    ]
