# Generated by Django 5.2.15 on 2026-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_add_mood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='theme_color',
            field=models.CharField(default='purple', help_text='Mã màu chủ đề được chọn, vd: purple, green, pink...', max_length=20, verbose_name='Màu chủ đề'),
        ),
    ]
