# Generated by Django 5.2.15 on 2026-07-05 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_mood_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Bản màu Vàng Tươi', max_length=100, unique=True, verbose_name='Tên bản màu')),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='Dùng làm màu chữ cho tag. VD: #FBBF24', max_length=30, verbose_name='Màu chính (Mã Hex)')),
                ('gradient_from', models.CharField(default='#FFD194', help_text='Dùng làm màu nền. VD: #FFD194', max_length=30, verbose_name='Gradient Bắt đầu')),
                ('gradient_to', models.CharField(default='#70E1F5', help_text='VD: #70E1F5', max_length=30, verbose_name='Gradient Kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chủ đề màu',
                'verbose_name_plural': 'Chủ đề màu',
                'db_table': 'social_mood_theme',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='mood',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='moodtype',
            name='gradient_from',
        ),
        migrations.RemoveField(
            model_name='moodtype',
            name='gradient_to',
        ),
        migrations.RemoveField(
            model_name='moodtype',
            name='text_color',
        ),
        migrations.AddField(
            model_name='mood',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Màu do user tự chọn khi viết custom mood', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods', to='social.moodtheme', verbose_name='Chủ đề màu tuỳ chọn'),
        ),
        migrations.AddField(
            model_name='moodtype',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Gắn một bản màu cho cảm xúc này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_types', to='social.moodtheme', verbose_name='Chủ đề màu (Theme)'),
        ),
    ]
