# Generated by Django 5.2.15 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_moodtheme_remove_mood_theme_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtype',
            name='emoji',
            field=models.CharField(help_text='Emoji đại diện cho cảm xúc này', max_length=10, verbose_name='Emoji'),
        ),
    ]
