# Generated by Django 5.2.15 on 2026-07-01 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('song', 'Bài hát'), ('playlist', 'Playlist'), ('comment', 'Bình luận'), ('user', 'Người dùng')], db_index=True, max_length=20, verbose_name='Loại')),
                ('target_type', models.CharField(blank=True, choices=[('song', 'Bài hát'), ('playlist', 'Playlist'), ('comment', 'Bình luận'), ('user', 'Người dùng')], max_length=10, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient_read_idx')],
            },
        ),
    ]
