# Generated by Django 5.2.15 on 2026-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Theo dõi mới'), ('follow_request', 'Yêu cầu kết bạn'), ('like', 'Lượt thích'), ('comment', 'Bình luận mới'), ('reply', 'Trả lời bình luận'), ('system', 'Hệ thống'), ('verify_result', 'Kết quả xác thực'), ('new_song', 'Bài hát mới')], db_index=True, max_length=20, verbose_name='Loại'),
        ),
    ]
