name: Deploy PlayMood to VPS

on:
  push:
    branches:
      - master
# Cấp quyền cho GitHub Actions được phép lưu trữ Image
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy code mới nhất mà bạn vừa đẩy lên
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Đăng nhập vào trạm trung chuyển GitHub (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Đóng gói Image và tải lên trạm trung chuyển
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/buildvps:${{github.sha}}

  deploy:
      needs: build-and-push
      runs-on: self-hosted
      steps:
        - name: Deploy application on VPS
          run: |
            cd /home/thanhnhan
            
            # Kéo bản cập nhật mới nhất từ GHCR
            docker compose pull app
            
            # Tái khởi động lại container app
            docker compose up -d app
            
            # Cập nhật DB và gom static files
            docker compose exec -T app python manage.py migrate --noinput
            docker compose exec -T app python manage.py collectstatic --noinput
            
            # Xóa các image cũ để giải phóng dung lượng ổ cứng
            docker image prune -f