# Generated by Django 5.2.14 on 2026-08-16 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0004_add_album_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gạt bỏ')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_by', to='music.song', verbose_name='Bài hát')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Gợi ý bị gạt bỏ',
                'verbose_name_plural': 'Gợi ý bị gạt bỏ',
                'db_table': 'recommendations_dismissal',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
